### ISSUE TITLE
报错，用不了呀

### ISSUE THREAD

**Issue by littleheary** [rabbitmask/WeblogicR2#2]
Traceback (most recent call last):
  File "WeblogicScanLot.py", line 137, in <module>
    run()
  File "WeblogicScanLot.py", line 134, in run
    board()
  File "WeblogicScanLot.py", line 48, in board
    poolmana(path)
  File "WeblogicScanLot.py", line 59, in poolmana
    rip =(ruleip.findall(rtar[i]))[0]
IndexError: list index out of range

**Comment by rabbitmask** [comment]
我处心积虑构造了半天也没出现你这个错误，什么系统？是用的py3么？

**Comment by littleheary** [comment]
这么尴尬的么。。。。。我py2和py3都试过，kali下跑的。

**Comment by Weifushi** [comment]
我也是报这个错。 。。

**Comment by rabbitmask** [comment]
```
└──╼ $python3 WeblogicScanLot.py 

__        __   _     _             _        ____                  
\ \      / /__| |__ | | ___   __ _(_) ___  / ___|  ___ __ _ _ __  
 \ \ /\ / / _ \ '_ \| |/ _ \ / _` | |/ __| \___ \ / __/ _` | '_ \ 
  \ V  V /  __/ |_) | | (_) | (_| | | (__   ___) | (_| (_| | | | |
   \_/\_/ \___|_.__/|_|\___/ \__, |_|\___| |____/ \___\__,_|_| |_|
                             |___/ 
                             By Tide_RabbitMask | V 2.2 

Welcome To WeblogicScan !!!
Whoami：rabbitmask.github.io

[*]任务加载成功，目标:192.168.246.1:80

[*]任务检测完成，目标:192.168.246.1:80

>>>>>End of task
```
### 我在 parrot下刚刚尝试的（同kali），我突然想到，你们ipresult.txt中格式是怎么样的，我这里接口读的是ip:port，目前来讲，应该不会在这里犯错，感谢反馈，有需要帮助请在此留言我会继续跟进，鞠躬。

**Comment by rabbitmask** [comment]
@Weifushi

**Comment by ghost** [comment]
windows有换行符
